### ISSUE TITLE
Github Action to update winget package on release

### ISSUE THREAD

**Issue by jo-chemla** [Victor-IX/Blender-Launcher-V2#141]
**Is your feature request related to a problem? Please describe.**
I've just submitted a PR https://github.com/microsoft/winget-pkgs/pull/172582 so that BlenderLauncher gets listed and can be installed on windows via `winget install blender-launcher` or `winget install VictorIXBlenderLauncher`. I've used [Komac](https://github.com/russellbanks/Komac) to create the manifest files available in the PR - crediting your github profile, name etc. 

It could be useful to add a github action on this repo so that the winget blender-launcher package gets updated on every github release.

**Describe the solution you'd like**

Here are two reference articles + action yml files made to keep the winget package up-to-date on every github release, via Github Actions. Requires a winget-token to be stored in security of the repo.  
 - [Use Winget-Releaser Github Action](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-), simpler but relies on external github action
 - [Producing packages for Windows Package Manager](https://techwatching.dev/posts/wingetcreate/) for a blank github action

```yaml
name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Package.Identifier
          token: ${{ secrets.WINGET_TOKEN }}
          # installers-regex: '\.exe$' # Only .exe files
```

```yaml
name: Submit Nushell package to Windows Package Manager Community Repository 

on:
  release:
    types: [published]

jobs:

  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $installerUrl = $github.release.assets | Where-Object -Property name -match 'windows.msi' | Select -ExpandProperty browser_download_url -First 1
          .\wingetcreate.exe update Nushell.Nushell -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.NUSHELL_PAT }}
```

**Describe alternatives you've considered**
Once the initial PR gets merged, anyone can update the BlenderLauncher package. But having a github action do it on every release would make sure the winget repo always has the latest version available
